version: "3"
services:
  bankly-co:
    image: bankly-co
    container_name: bankly-co
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8081:8080"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://bankly-db:5432/bankly
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
        - bankly-db

  bankly-db:
    image: postgres
    container_name: bankly-db
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=bankly

