version: "3"
services:
  transactions-management:
    image: m2-backend
    container_name: m2-TransactionsManagement
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8082:8080"

    depends_on:
        - m2-transactionsManagement-db
  m2-transactionsManagement-db:
    image: mongo
    container_name: m2-transactionsManagement-db
    ports:
        - "27017:27017"
